### ISSUE TITLE
Keep getting Assertion errors

### ISSUE THREAD

**Issue by zhiqihuang** [NeuCLIR/download-collection#3]
Hi 

Trying to download the collection. But keep getting "Assertion error, retrying XX times"

The All files progress bar indicates downloading the collection needs 300 hours. Is it normal?

Thanks

**Comment by dlawrie** [comment]
Thanks for letting us know. Have you registered for TREC?

From: Zhiqi ***@***.***>
Date: Monday, June 19, 2023 at 8:32 PM
To: NeuCLIR/download-collection ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NeuCLIR/download-collection] Keep getting Assertion errors (Issue #3)

Hi

Trying to download the collection. But keep getting "Assertion error, retrying XX times"

The All files progress bar indicates downloading the collection needs 300 hours. Is it normal?

Thanks

**Comment by zhiqihuang** [comment]
Yes. I registered for TREC 23. My group ID is CIIR. I tried to download the collection from [here](https://trec.nist.gov/act_part/tracks2022.html). It says 503 Service Unavailable.

**Comment by dlawrie** [comment]
The collection is supposed to be available directly from NIST. We just realized that Ian removed those links. I’ve sent him a message and will connect with him tomorrow to make sure those links get restored. Thanks for bringing this to our attention.

Dawn

From: Zhiqi ***@***.***>
Date: Monday, June 19, 2023 at 11:06 PM
To: NeuCLIR/download-collection ***@***.***>
Cc: Dawn Lawrie ***@***.***>, Comment ***@***.***>
Subject: Re: [NeuCLIR/download-collection] Keep getting Assertion errors (Issue #3)

Yes. I registered for TREC 23. My group ID is CIIR. I tried to download the collection from here<https://trec.nist.gov/act_part/tracks2022.html>. It says 503 Service Unavailable.

**Comment by zhiqihuang** [comment]
Awesome. Thanks for your quick response. I will close this issue.

**Comment by dlawrie** [comment]
No problem. It turns out that I have links to the document collection. I just sent them to the address you provided when you registered for TREC.

From: Zhiqi ***@***.***>
Date: Monday, June 19, 2023 at 11:15 PM
To: NeuCLIR/download-collection ***@***.***>
Cc: Dawn Lawrie ***@***.***>, Comment ***@***.***>
Subject: Re: [NeuCLIR/download-collection] Keep getting Assertion errors (Issue #3)

Awesome. Thanks for your quick response. I will close this issue.
